version: '3.8'
services:
    slack-clone:
        image: slack-clone
        container_name: slack-clone
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '3000:80'
        restart: always
        