version: '3.9'
services:
    slack-clone-web:
        image: slack-clone-web
        container_name: slack-clone-web
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '3000:80'
        restart: always
        stdin_open: true
        tty: true
        